// Stanze dei Memo tesoro (forme dalla wiki giapponese Grovyle, stanza 114 ricostruita da schermate).
window.MemoRoomGallery = [
  {
    "specialFloor": 114,
    "expertOnly": true,
    "width": 7,
    "height": 15,
    "grid": [
      "#######",
      "###S###",
      "##...##",
      "#..L..#",
      "#.LLL.#",
      "#.....#",
      "##...##",
      "###.###",
      "###.###",
      "###.###",
      "#.....#",
      "#..P..#",
      "#.PPP.#",
      "#.....#",
      "#######"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": false,
      "breakWall": false,
      "chestnut": false,
      "wind": false,
      "warp": false
    },
    "reconstructedFromScreens": true,
    "missingMap": false,
    "noteKey": "memo114ResearchNote",
    "warningKey": "memo114Warning",
    "observedLootKey": "memo114ObservedLoot"
  },
  {
    "specialFloor": 115,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "####....####",
      "##........##",
      "##........##",
      "#.........~#",
      "#...~~~...~#",
      "#...~~~~~~~#",
      "#S.....T~~~#",
      "##.......~##",
      "##........##",
      "####....####",
      "############"
    ],
    "flags": {
      "player": false,
      "key": false,
      "water": false,
      "breakWall": false,
      "chestnut": false,
      "wind": false,
      "warp": false
    },
    "sample": null
  },
  {
    "specialFloor": 116,
    "width": 12,
    "height": 13,
    "grid": [
      "############",
      "#....##....#",
      "#....##..S.#",
      "#..........#",
      "#..........#",
      "###FFFF.F###",
      "###F....F###",
      "###F.FFFF###",
      "#..........#",
      "#.PP.##....#",
      "#.PP.##..T.#",
      "#....##....#",
      "############"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": false,
      "breakWall": false,
      "chestnut": false,
      "wind": true,
      "warp": false
    }
  },
  {
    "specialFloor": 117,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "####PPPP####",
      "####PTPP####",
      "####P.PP####",
      "####....####",
      "####....####",
      "###......###",
      "#..........#",
      "#..........#",
      "#........S.#",
      "#..........#",
      "############"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": false,
      "breakWall": false,
      "chestnut": false,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 118,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "####..~~~.........####",
      "###..~~~~..........###",
      "##.F.~~~~~~.........##",
      "#.....~~~~~..........#",
      "#.....~~~~~.F~~~...F.#",
      "#.....#~~~..~~~#.....#",
      "#.....#.....~~~#.....#",
      "#.....#~~....~~#.....#",
      "#.....#~~~~....#.....#",
      "#.....#~~~~~...#.....#",
      "#.....#~~.~~~..#C.S..#",
      "#.....#..T.~~..#.....#",
      "#.....#........#.....#",
      "#....~#........#...C.#",
      "#C.C~~##########.....#",
      "#C.C~~~~.............#",
      "#....~~~..C..........#",
      "##..................##",
      "###...........F....###",
      "####..............####",
      "######################"
    ],
    "flags": {
      "player": false,
      "key": false,
      "water": false,
      "breakWall": false,
      "chestnut": true,
      "wind": true,
      "warp": false
    }
  },
  {
    "specialFloor": 119,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "#..................~~#",
      "#..................~~#",
      "#...................~#",
      "#...................~#",
      "#....#############...#",
      "#....#~~~~.......#...#",
      "#....#~~~........#...#",
      "#....#~..........#...#",
      "#....#...#####...#...#",
      "#....#.......#.......#",
      "#.S..#.....T.#.......#",
      "#....#.......#.......#",
      "#....#...#####...#...#",
      "#....#...........#...#",
      "#....#...........#...#",
      "#....#...........#...#",
      "#~...#############...#",
      "#~~..................#",
      "#~~~~~~..............#",
      "#~~~~~~~.............#",
      "######################"
    ],
    "flags": {
      "player": false,
      "key": false,
      "water": false,
      "breakWall": false,
      "chestnut": false,
      "wind": false,
      "warp": false
    },
    "sample": null
  },
  {
    "specialFloor": 120,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "#.........##.........#",
      "#.S.......##.........#",
      "#....~....##..~...~..#",
      "#.........##.........#",
      "#~.~.W.~.~##..~.W.~..#",
      "#.........##.........#",
      "#....~....##..~...~..#",
      "#.........##.T.......#",
      "#.........##.........#",
      "######################",
      "######################",
      "#.........##.........#",
      "#.........##.........#",
      "#..PPPPP..##...~.~...#",
      "#..P...P..##.........#",
      "#..P.W.P..##..~.W.~..#",
      "#..P...P..##.........#",
      "#..PPPPP..##...~.~...#",
      "#.........##.........#",
      "#.........##.........#",
      "######################"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": false,
      "breakWall": false,
      "chestnut": false,
      "wind": false,
      "warp": true
    },
    "sample": null
  },
  {
    "specialFloor": 121,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "#W.~~~~....#",
      "#.T~~~~....#",
      "#~~~~~.....#",
      "#~~~~......#",
      "#~~........#",
      "#..........#",
      "#..........#",
      "#..........#",
      "#BBB.....S.#",
      "#BFB.......#",
      "############"
    ],
    "flags": {
      "player": false,
      "key": false,
      "water": true,
      "breakWall": false,
      "chestnut": false,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 122,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "#...~.F~...#",
      "#...~..~...#",
      "#.S.~..~...#",
      "#...~..~...#",
      "#...~..~.T.#",
      "#...~..~...#",
      "#.F.~..~.F.#",
      "#...~..~...#",
      "#...~..~...#",
      "#...~F.~...#",
      "############"
    ],
    "flags": {
      "player": false,
      "key": false,
      "water": true,
      "breakWall": false,
      "chestnut": false,
      "wind": true,
      "warp": false
    },
    "sample": null
  },
  {
    "specialFloor": 123,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "#..........#",
      "#.S........#",
      "#..........#",
      "#...~~~~...#",
      "#...~PT~...#",
      "#...~WP~...#",
      "#...~~~~...#",
      "#..........#",
      "#..........#",
      "#..........#",
      "############"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": true,
      "breakWall": false,
      "chestnut": false,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 124,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "#W..~~~~~B...B....~~~#",
      "#....~~B~B.B.B.....~~#",
      "#..T.~~B.B.B.B.....~~#",
      "#......B.B.B.B.....~~#",
      "#......B.B.B.BW.....~#",
      "#BBBBBBB.B.B.BBBBBBBB#",
      "#C.......B.B........P#",
      "#.BBBBBBBBCBBBBBBBBBB#",
      "#.BW.........B.......#",
      "#.B..........B.......#",
      "#.B..........B...S...#",
      "#.B......B.BBB.......#",
      "#.B......B.B.........#",
      "#.B......B.B........W#",
      "#.BBBBBBBB.B..BBBBBBB#",
      "#..........B..BW.....#",
      "#BBBBBBBB..B..B..PPPC#",
      "#C.....WB..B..B..PPPC#",
      "#C......B.....B..PPPC#",
      "#C......B.....B..CCCC#",
      "######################"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": true,
      "breakWall": true,
      "chestnut": true,
      "wind": false,
      "warp": true
    }
  },
  {
    "specialFloor": 125,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "#.......B......WB....#",
      "#.......B......BB...B#",
      "#..BBBBBBBB...BB...BB#",
      "#..BBPPBBB...BB...BB.#",
      "#..BPPPBB...BB...BB..#",
      "#....PBB...BB...BB...#",
      "#....BB...BB...BB...B#",
      "#...BB...BB...BB...BB#",
      "#..BB...BBPP.BB...BBW#",
      "#WBB~~~BBPPPBB...BB..#",
      "#BB~~~BB.FPBB...BB...#",
      "#B.~~BB...BB...BB.T.B#",
      "#...BB...BB...BB...BB#",
      "#..BB...BB...BB~~~BB.#",
      "#..B...BB...BB~~~BB..#",
      "#.....BB...BB..~BB...#",
      "#....BB...BB...BB....#",
      "#...BB...BB...BB...P.#",
      "#.S...............PP.#",
      "#....................#",
      "######################"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": true,
      "breakWall": true,
      "chestnut": false,
      "wind": true,
      "warp": false
    }
  },
  {
    "specialFloor": 126,
    "width": 20,
    "height": 20,
    "grid": [
      "####################",
      "#W......~~~~~~....W#",
      "#.S.......~~~......#",
      "#.......####~...T..#",
      "#......######......#",
      "#.....##.WW.##...~~#",
      "#....##......##..~~#",
      "#...##.CCCCCC.##~~~#",
      "#..##..CPPPPC..##~~#",
      "#..##..CPPPPC..##.~#",
      "#..##..CPPPPC..##..#",
      "#..##..CPPPPC..##..#",
      "#...##.CCCCCC.##...#",
      "#....##......##....#",
      "#.....##.WW.##.....#",
      "#......######......#",
      "#.......####.......#",
      "#..................#",
      "#W................W#",
      "####################"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": true,
      "breakWall": false,
      "chestnut": true,
      "wind": false,
      "warp": true
    }
  },
  {
    "specialFloor": 127,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "######W....~~~########",
      "######......~~########",
      "######.......~##.....#",
      "######..PPPP.~##.BBB.#",
      "######..PPPP..##.BTB.#",
      "######........##.....#",
      "######........##W....#",
      "######........####.###",
      "#########.########B###",
      "#########.########.###",
      "#########.##.........#",
      "#.....###B##.........#",
      "#.....###.##.........#",
      "#.....###.##.........#",
      "#.....###.##.........#",
      "#F................F..#",
      "#.....######.........#",
      "#.....######.........#",
      "#..S..######.........#",
      "#.....######.........#",
      "######################"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": false,
      "breakWall": true,
      "chestnut": false,
      "wind": true,
      "warp": false
    }
  },
  {
    "specialFloor": 128,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "#.....CCC............#",
      "#....................#",
      "#.....CCC............#",
      "#...BBBBBBBBBB..BB...#",
      "#...B............B...#",
      "#...B............B...#",
      "#...B............B...#",
      "#...B...BBBBBB...B...#",
      "#...B...B..T.B...B...#",
      "#...B...B....B...B...#",
      "#...B...B....B...B...#",
      "#...B...BW...B...B...#",
      "#...B...BBBBBB...B...#",
      "#...B.....CCCC...B...#",
      "#...B............B...#",
      "#...B.....CCCC...B...#",
      "#...BB..BBBBBBBBBB...#",
      "#.......~~~..........#",
      "#......~~~.S.........#",
      "#.....~~~............#",
      "######################"
    ],
    "flags": {
      "player": false,
      "key": false,
      "water": false,
      "breakWall": true,
      "chestnut": true,
      "wind": false,
      "warp": false
    },
    "sample": null
  },
  {
    "specialFloor": 129,
    "width": 21,
    "height": 19,
    "grid": [
      "#####################",
      "#....WBB............#",
      "#.PPP.BB...........W#",
      "#~~~~~BB............#",
      "#~~~~~BB.....BB.....#",
      "#..B..BB..B..BB.....#",
      "#.....BB.....BB.B.B.#",
      "#..B..BB..B..BBB.B.B#",
      "#.....BB.....BB.B.B.#",
      "#.....BB..S..BB.....#",
      "#.....BB.....BB..T.W#",
      "#..B..BB..B..BB.....#",
      "#.....BB.....BB.B.B.#",
      "#..B..BB..B..BB~~~~~#",
      "#.....BB.....BB~~~~~#",
      "#............BB~~~~~#",
      "#............BB.PPP.#",
      "#............BBWPPP.#",
      "#####################"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": false,
      "breakWall": true,
      "chestnut": false,
      "wind": false,
      "warp": true
    }
  },
  {
    "specialFloor": 130,
    "width": 17,
    "height": 18,
    "grid": [
      "#################",
      "#.......#.......#",
      "#..C.C..#...P...#",
      "#.C.C.C.#..PPP..#",
      "#..CSC..#.PPTPP.#",
      "#.C.C.C.#..PPP..#",
      "#..C.C..#...P...#",
      "#.......#.......#",
      "#...F...##K######",
      "#...F...........#",
      "#...F.........F.#",
      "#...F.........F.#",
      "#.FFFFFFFFFF..F.#",
      "#...F.........F.#",
      "#...F.........F.#",
      "#.............F.#",
      "#...............#",
      "#################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": false,
      "breakWall": false,
      "chestnut": true,
      "wind": true,
      "warp": false
    }
  },
  {
    "specialFloor": 131,
    "width": 12,
    "height": 22,
    "grid": [
      "############",
      "#####.######",
      "###...~PPW##",
      "###...~PPP##",
      "##....~~PP##",
      "#####.~~~~##",
      "#...#.....##",
      "#.T.#.....##",
      "#...#.C....#",
      "##K##......#",
      "#........C.#",
      "#....C.....#",
      "#........S.#",
      "#..C.......#",
      "#.........##",
      "#.........##",
      "#.........##",
      "#~~.......##",
      "##~~.....###",
      "##~~....####",
      "####...#####",
      "############"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": true,
      "wind": false,
      "warp": false
    },
    "sample": null
  },
  {
    "specialFloor": 132,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "####...~##..##########",
      "##W...~~~...##########",
      "#P....~~...~##########",
      "#PP..#~~...~##########",
      "##PP###...~~##########",
      "########...~####...###",
      "########....C##..T..##",
      "#######.....CC.....###",
      "##WP#~~.....CC....####",
      "##PP~~~.....C....#####",
      "##P.~~.......C########",
      "##P.~~......##########",
      "#######.....##########",
      "#########K###....#####",
      "#######...........####",
      "#######.............##",
      "##..##...............#",
      "#....................#",
      "#..S.........##.....##",
      "##.........####....###",
      "######################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": true,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 133,
    "width": 22,
    "height": 18,
    "grid": [
      "######################",
      "#......BPPPP.WB......#",
      "#......BPPPP..B......#",
      "#..S...B......B......#",
      "#......B......B......#",
      "#......B......B......#",
      "#BB..BBBBBBKBBBBB..BB#",
      "#.............C......#",
      "#.............C......#",
      "#......C.............#",
      "#......C.........B.B.#",
      "#BBBBBBBBBB..BBBBBBBB#",
      "#......B~~.....B.....#",
      "#.W...~~~~....BB.~~~.#",
      "#....~~~~......B.~T~.#",
      "#....~~B~.....BB.~~~.#",
      "#.....~BB......B....W#",
      "######################"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": true,
      "breakWall": true,
      "chestnut": true,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 134,
    "width": 26,
    "height": 19,
    "grid": [
      "##########################",
      "########~..#####~~~..#####",
      "#####~~~~.......~~~~...###",
      "####~~~~.........~~~~..###",
      "###..~####........~~~..###",
      "##...~#.W#.........~~~..##",
      "##....#.T#.....BBBB~~~..##",
      "##....#..#.....BWPB.~....#",
      "#CCCCC#K##.....BPPB....S.#",
      "#.......C......BPPB......#",
      "#..............BBBB......#",
      "#~......................##",
      "#~~.....BBBBB...........##",
      "#~~.....BPPWB...FF.....###",
      "##~~....BPPPB...FF.....###",
      "##~~....B~~~~~........####",
      "####..~~~~~~~~~......#####",
      "#######~~~~~##############",
      "##########################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": false,
      "breakWall": true,
      "chestnut": true,
      "wind": true,
      "warp": false
    },
    "sample": null
  },
  {
    "specialFloor": 135,
    "width": 30,
    "height": 20,
    "grid": [
      "#############....#############",
      "############......############",
      "############..FF..############",
      "#############....#############",
      "#..#########......#########P.#",
      "....######..........######....",
      "..B..####............####..B..",
      "P.BB..##..............##..BB..",
      "..BBB..#.....BBBB.....#..BBB..",
      "..BBBB......BB~~BB......BBBB..",
      "#.....B....BB~~~~BB....B.....#",
      "#...PPB..BBB~~TP~~BBB..B.....#",
      "..BBBBB..BBB~~PW~~BBB..BBBBB.P",
      "..BBBBB....BB~~~~BB....BBBBB.P",
      "#....BB.....BB~~BB.....BB...P#",
      "##...BBB.....BBBB.....BBB...##",
      "##..BBBB..............BBBB..##",
      "##P.BBB........S.......BBB..##",
      "###......#..........#......###",
      "####...#####......#####...####"
    ],
    "flags": {
      "player": true,
      "key": false,
      "water": true,
      "breakWall": true,
      "chestnut": false,
      "wind": true,
      "warp": false
    }
  },
  {
    "specialFloor": 136,
    "width": 25,
    "height": 20,
    "grid": [
      "#########################",
      "#.....###################",
      "#.....#.....#############",
      "#..S..#.....#.....#######",
      "#.....#..P..#.....#.....#",
      "#.....#.....#..T..#.....#",
      "###.###.....#.....#..P..#",
      "###.#####.###.....#.....#",
      "###.#####.#####K###.....#",
      "###.#####.#####~#####.###",
      "###.#####.#####~#####.###",
      "###.#####.#####~###.....#",
      "###.#####.###~~~~~#.....#",
      "###.###.....#.~~~~#..C..#",
      "#.....#.....#...~.#.....#",
      "#.....#.....#...........#",
      "#..C..#...........#######",
      "#...........#############",
      "#.....###################",
      "#########################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": true,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 137,
    "width": 30,
    "height": 20,
    "grid": [
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~........~~~~~~~~~~~~~~~~~~~",
      "~~~..####..~~~~~~~~~~~~~~~~~~~",
      "~~~..#T.#..~~~~~~~~~~~~~~~~~~~",
      "~~~..#..#..~~~~~~~~~~~~~~~~~~~",
      "~~~..##K#F.~~~~~~~~F.....~~~~~",
      "~~~........~~~~~~~~...PP.~~~~~",
      "~~~~~~~~~~~~~~~~~~~...PP.~~~~~",
      "~~~~~~~~~~~~~~~~~~~......~~~~~",
      "~~~~~~~~~~~~F...~~~......~~~~~",
      "~~~~~~~~~~~~..S.~~~......~~~~~",
      "~~~~~~~~~~~~....~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~....~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~....~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~...F~~~~~~~~~~.....~~~~~~~~",
      "~~~PP..~~~~~~~~~~.....~~~~~~~~",
      "~~~PP..~~~~~~~~~~.....~~~~~~~~",
      "~~~~~~~~~~~~~~~~~...F.~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": false,
      "wind": true,
      "warp": false
    },
    "sample": null
  },
  {
    "specialFloor": 138,
    "width": 23,
    "height": 22,
    "grid": [
      "#######################",
      "######~~~~~~#....######",
      "#####~~~~~~~#.....#####",
      "####~~~~~~~~.......####",
      "###~PP~~~~~~.....S..###",
      "##~PPP~~~~~~.........##",
      "#~~WP~~~~~~~#.........#",
      "#~~~~~~~~~~~#.........#",
      "#~~~~~~########...#####",
      "#~~~~~~#.....#~~~~~~~~#",
      "#~~~~~~#..T..#~~~~~~~~#",
      "#~~~~~~#.....#~~~~~~~~#",
      "#~~~~~~#.....#~~~~~~~~#",
      "##.#######K###~~~~~~~~#",
      "#C.C..F.C....#~~~~~~~~#",
      "#..........W.#~~~~PP~~#",
      "##..F...F....#~~~PPW~##",
      "###..W........~~~PP~###",
      "####......F..#~~~~~####",
      "#####..F....C#~~~~#####",
      "######...C...#~~~######",
      "#######################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": true,
      "wind": true,
      "warp": true
    },
    "sample": null
  },
  {
    "specialFloor": 139,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "#.W..###F..#",
      "#~~~~~~#~~~#",
      "#~~~~~~~~~~#",
      "#~~~~~~#~~~#",
      "#....F##.###",
      "#.....#...W#",
      "###K###...W#",
      "#.....#PPPW#",
      "#....S#PTPW#",
      "#.....#PPPW#",
      "############"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": false,
      "wind": true,
      "warp": true
    }
  },
  {
    "specialFloor": 140,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "#...~~~#.T.#",
      "#...#~~#...#",
      "#...#..##K##",
      "#.FC#~~#~~~#",
      "#C.C#~~#.WW#",
      "#CC.#F~#~~~#",
      "#...#~F#WW.#",
      "#...#F~#~~~#",
      "#.S.#~F#~~~#",
      "#...#~~~~~~#",
      "############"
    ],
    "flags": {
      "player": false,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": true,
      "wind": true,
      "warp": true
    },
    "sample": null
  },
  {
    "specialFloor": 141,
    "width": 12,
    "height": 12,
    "grid": [
      "############",
      "#PPPBBBBBBB#",
      "#PPPB~~~~~B#",
      "#PPPB~###~B#",
      "#PPPB~#T#~B#",
      "#C.CB~#K#~B#",
      "#.C.B~~~~~B#",
      "#C.CBBBBBBB#",
      "#..........#",
      "#..........#",
      "#.........S#",
      "############"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": true,
      "chestnut": true,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 142,
    "width": 21,
    "height": 21,
    "grid": [
      "#####################",
      "#####...#~~~#####...#",
      "##.....W#~~~...##.T.#",
      "##.##...#~~~##.##...#",
      "##.###.###.###.###K##",
      "#~~~##.###.##...##.##",
      "#~~~##.###.##.C.##.##",
      "#~~~##.###.##...##.##",
      "##.###.###.###.###.##",
      "#...#~~~#...##.###B##",
      "#.C.#~~~#...##.###C##",
      "#...#~~~#...##.###B##",
      "##.###.###.###.###.##",
      "##.###.##...##.##P..#",
      "##.###.##...##.##P.W#",
      "##.###.##..S##.##P..#",
      "##.###.###.###.###.##",
      "#PPP##.###.###.###.##",
      "#PPP##.....###.....##",
      "#WPP#################",
      "#####################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": true,
      "chestnut": true,
      "wind": false,
      "warp": false
    }
  },
  {
    "specialFloor": 143,
    "width": 17,
    "height": 22,
    "grid": [
      "#################",
      "#W..###PPP###...#",
      "#.C....PPP###.T.#",
      "#...###PPP###...#",
      "##~###########K##",
      "##~###########.##",
      "##~###########.##",
      "#..~###...###...#",
      "#.F~###.F.....C.#",
      "#~~~###...###...#",
      "##.#...###...#~##",
      "##.#.W.###.W.#~##",
      "##.#...###...#~##",
      "#S..###...###...#",
      "#.F.###.F.....C.#",
      "#...###...###...#",
      "##.#####.#####.##",
      "##.#####.#####.##",
      "##.####...####.##",
      "##.............##",
      "#######...#######",
      "#################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": false,
      "chestnut": true,
      "wind": true,
      "warp": true
    },
    "sample": null
  },
  {
    "specialFloor": 144,
    "width": 22,
    "height": 22,
    "grid": [
      "######################",
      "#..T..#W~~~~~~WBPPWPP#",
      "#.....#.~~~~~~.BPPPPP#",
      "###K###.~BBBB~.BBBBBB#",
      "#.......~B..B~.......#",
      "#~~~~~~~~B..B~~~~~~~~#",
      "#BBBBBBBBB..BBBBBBBBB#",
      "#....................#",
      "#.C................F.#",
      "#...F.......S..C.F...#",
      "#......C.............#",
      "#.................C..#",
      "##..C....F..C.......##",
      "###.............C..###",
      "####...C..........####",
      "#####.........F..#####",
      "#####.....CC.....#####",
      "#####.F.BBBBBB...#####",
      "#####...BPPPPB...#####",
      "#####...BPPPPB...#####",
      "#####...BPPWPB...#####",
      "######################"
    ],
    "flags": {
      "player": true,
      "key": true,
      "water": true,
      "breakWall": true,
      "chestnut": true,
      "wind": true,
      "warp": false
    },
    "sample": null
  }
];

// Missioni Memo tesoro reali generate dal gioco giapponese (wiki Grovyle), lette con la tabella JP.
// Il gioco vale per tutte le regioni: la pagina le converte nella regione scelta.
window.MemoRealExamples = [
  {
    "code": "H6JHJY79KYHQ-5R+Q-K#5QFY&@6=WJ#X+J",
    "region": "jp",
    "specialFloor": 115,
    "dungeon": 1,
    "floor": 2,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "@%X7826K+N&1CP5F5K6K1YJQN4JP#=M0Q7",
    "region": "jp",
    "specialFloor": 116,
    "dungeon": 6,
    "floor": 6,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "T5JK&C21FFSFF+X1@C+118C0NN2QC0Y4F1",
    "region": "jp",
    "specialFloor": 117,
    "dungeon": 3,
    "floor": 5,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "N184WJM-T@6&7W%T%R20N3=&R7T2-S45#2",
    "region": "jp",
    "specialFloor": 117,
    "dungeon": 7,
    "floor": 10,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "%+QFMM&YTHYJSQX8F#69TP%#73R=H951RC",
    "region": "jp",
    "specialFloor": 118,
    "dungeon": 7,
    "floor": 10,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "TF%01W8&JPP91K=3+-8X#JHM88401Q@H+N",
    "region": "jp",
    "specialFloor": 118,
    "dungeon": 8,
    "floor": 9,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "N-#YXWP7#32=4-S6RRN17NR&&T+T7Q5PPC",
    "region": "jp",
    "specialFloor": 118,
    "dungeon": 20,
    "floor": 13,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "SN133-Q#F5-8QQ+8X7#4W42+RXM%TJ%@WS",
    "region": "jp",
    "specialFloor": 119,
    "dungeon": 12,
    "floor": 7,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "HT62JCMX#7K56PK4P8X597J0&3#9-WY21#",
    "region": "jp",
    "specialFloor": 120,
    "dungeon": 6,
    "floor": 8,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "X+#34&NPC8N@3X8@7Y&&J20W9=-XP6R-PM",
    "region": "jp",
    "specialFloor": 122,
    "dungeon": 12,
    "floor": 9,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "N7QHFCR4#08-9F8H0QHHS1@+RH+@FJ9SSP",
    "region": "jp",
    "specialFloor": 124,
    "dungeon": 35,
    "floor": 6,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "314-C99K3=3%NWXN72&%K1WKR7@XR1TX00",
    "region": "jp",
    "specialFloor": 125,
    "dungeon": 3,
    "floor": 6,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "QH9YP8R#4-SHMHP%W7P1&@9%&=XS+#TH#M",
    "region": "jp",
    "specialFloor": 126,
    "dungeon": 7,
    "floor": 6,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "QTMK=N1043Y5+X%-NJF9SWYTP1-J8%&X#1",
    "region": "jp",
    "specialFloor": 126,
    "dungeon": 17,
    "floor": 8,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "T#N76P1Q9NP=MT905911C5KF85F1R3PT12",
    "region": "jp",
    "specialFloor": 127,
    "dungeon": 3,
    "floor": 6,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "#1%K@C##M#31Q7Q3X1W=PC678W8Q9W+3T5",
    "region": "jp",
    "specialFloor": 127,
    "dungeon": 10,
    "floor": 14,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "KNFSCK@2CC4T4&F@%1YP%%H@790PM7JPF9",
    "region": "jp",
    "specialFloor": 129,
    "dungeon": 3,
    "floor": 3,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "0QYM&1T=+@W5@WYRK46QYQ9%R5TRXHH5##",
    "region": "jp",
    "specialFloor": 129,
    "dungeon": 12,
    "floor": 6,
    "source": "wiki.grovyle.net"
  },
  {
    "code": "Y6M61-63MPK+=7WNR7+1FQ#Q&7S50TQ&-C",
    "region": "jp",
    "specialFloor": 129,
    "dungeon": 14,
    "floor": 6,
    "source": "wiki.grovyle.net"
  }
];
